# Switched from $commit_SHA to $SHORT_SHA

steps:
  - name: "maven:3.9.1-eclipse-temurin-11"
    entrypoint: "mvn"
    args: [ 'clean', 'package' ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/video-streaming-app:1"
      - "."
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/video-streaming-app:1"
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - "run"
      - "--filename=kubernetes.tpl.yaml"
      - "--location=europe-southwest1-a"
      - "--cluster=video-streaming-cluster"


images: ["gcr.io/$PROJECT_ID/video-streaming-app:1"]

