# Switched from $commit_SHA to $SHORT_SHA

steps:
  - name: "maven:3.9.1-eclipse-temurin-11"
    entrypoint: "mvn"
    args: [ 'clean', 'package' ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/video-streaming-app:$SHORT_SHA"
      - "."
  # timeout: 1800s
  # - name: 'gcr.io/cloud-builders/gsutil'
  #  args: ['cp', '-r', 'k8s/*', 'gs://$PROJECT_ID-kubernetes-manifests/vowo-dev']
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/video-streaming-app:$SHORT_SHA"

  # [START cloudbuild-trigger-cd]
  # This step clones the hello-cloudbuild-env repository
  - name: "gcr.io/cloud-builders/gcloud"
    id: Clone env repository
    entrypoint: /bin/sh
    args:
      - "-c"
      - |
        gcloud source repos clone video-streaming-repo && \
        git checkout -b kubernetes && \
        git config --global user.email "video-streaming-app-account@video-streaming-paas.iam.gserviceaccount.com"

  # This step generates the new manifest
  - name: "gcr.io/cloud-builders/gcloud"
    id: Generate manifest
    entrypoint: /bin/sh
    args:
      - "-c"
      - |
        sed "s/GOOGLE_CLOUD_PROJECT/${PROJECT_ID}/g" kubernetes.tpl.yaml | \
        sed "s/COMMIT_SHA/${SHORT_SHA}/g" > video-streaming-repo/kubernetes.yaml

  # This step pushes the manifest back to hello-cloudbuild-env
  - name: "gcr.io/cloud-builders/gcloud"
    id: Push manifest
    entrypoint: /bin/sh
    args:
      - "-c"
      - |
        set -x && \
        git add . && \
        git commit -m "Deploying image gcr.io/${PROJECT_ID}/video-streaming-app:${SHORT_SHA}
        Built from commit ${COMMIT_SHA} of repository video-streaming-app" && \
        git push
#  - name: "gcr.io/cloud-builders/gke-deploy"
#    args:
#      - "run"
#      - "--filename=kubernetes.tpl.yaml"
#      - "--location=europe-southwest1-a"
#      - "--cluster=video-streaming-cluster"

# [END cloudbuild-trigger-cd]
# timeout: 2000s
images: ["gcr.io/$PROJECT_ID/video-streaming-app:$SHORT_SHA"]

