spring:
  datasource:
      url: jdbc:mysql://10.122.144.3/video-streaming-db
      username: root
      password: Ab6jidjK3LbAt7
      driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://34.116.161.117/video-streaming-db
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  cloud:
    gcp:
      sql:
        instance-connection-name: video-stream-instance:europe-west3:video-streaming-db
        database-name: video-streaming-db
      config:
        credentials:
          location: video-streaming-paas.json