spring:
  datasource:
    url: jdbc:mysql://34.116.161.117/video-streaming-db
    username: root
    password: Yo>fr5),):)p%yqE
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  spring:
    cloud:
      gcp:
        config:
          credentials:
            location: delta-env-279714-0f6e13cf1df3.json
