micronaut:
  application:
    name: videoStreamCloud
jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none
datasources:
  default:
    url: jdbc:h2:mem:my_db
    driverClassName: org.h2.Driver
    username: sa
    password:
