spring:
  datasource:
    url: jdbc:mysql://video-stream-database.ciw7bd74o9ne.eu-central-1.rds.amazonaws.com/video-stream-database
    username: admin
    password: sAjDBkGrqqBK
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      show-sql: false
      hibernate:
        ddl-auto: update
  servlet:
    mulipart:
      max-file-size: 100MB
      max-request-size: 100MB
